import sqlite3
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, 'database', 'questions.db')
SCHEMA_PATH = os.path.join(BASE_DIR, 'database', 'schema.sql')

# Ensure database and table exist
with sqlite3.connect(DB_PATH) as conn:
    with open(SCHEMA_PATH, 'r') as f:
        conn.executescript(f.read())

preguntas = [{'opcion_a': 'O(n)',
  'opcion_b': 'O(log n)',
  'opcion_c': 'O(n log n)',
  'opcion_d': 'O(1)',
  'pregunta': '¿Cuál es la complejidad temporal de la búsqueda binaria?',
  'resultado': 'O(log n)'},
 {'opcion_a': 'SMTP',
  'opcion_b': 'FTP',
  'opcion_c': 'SSH',
  'opcion_d': 'HTTP',
  'pregunta': '¿Qué protocolo se utiliza principalmente para enviar correos electrónicos?',
  'resultado': 'SMTP'},
 {'opcion_a': 'Red',
  'opcion_b': 'Transporte',
  'opcion_c': 'Enlace de datos',
  'opcion_d': 'Aplicación',
  'pregunta': '¿En qué capa del modelo OSI se encuentra el protocolo TCP?',
  'resultado': 'Transporte'},
 {'opcion_a': 'Cola',
  'opcion_b': 'Pila',
  'opcion_c': 'Árbol',
  'opcion_d': 'Grafo',
  'pregunta': '¿Qué estructura de datos utiliza la política FIFO?',
  'resultado': 'Cola'},
 {'opcion_a': 'Quicksort',
  'opcion_b': 'Dijkstra',
  'opcion_c': 'Floyd-Warshall',
  'opcion_d': 'Prim',
  'pregunta': '¿Qué algoritmo se emplea comúnmente para encontrar el camino más corto en grafos?',
  'resultado': 'Dijkstra'},
 {'opcion_a': 'MongoDB',
  'opcion_b': 'Oracle',
  'opcion_c': 'Redis',
  'opcion_d': 'Neo4j',
  'pregunta': '¿Cuál de los siguientes es un sistema de gestión de bases de datos relacional?',
  'resultado': 'Oracle'},
 {'opcion_a': 'SQL',
  'opcion_b': 'HTML',
  'opcion_c': 'CSS',
  'opcion_d': 'XML',
  'pregunta': '¿Qué lenguaje se utiliza para definir esquemas de bases de datos relacionales?',
  'resultado': 'SQL'},
 {'opcion_a': 'Subversion',
  'opcion_b': 'Mercurial',
  'opcion_c': 'Git',
  'opcion_d': 'CVS',
  'pregunta': '¿Qué sistema de control de versiones es ampliamente utilizado y distribuido?',
  'resultado': 'Git'},
 {'opcion_a': 'Funciones recursivas',
  'opcion_b': 'Clases y objetos',
  'opcion_c': 'Bloques anónimos',
  'opcion_d': 'Programación funcional',
  'pregunta': '¿Cuál es la principal característica de la programación orientada a objetos?',
  'resultado': 'Clases y objetos'},
 {'opcion_a': 'Compilador',
  'opcion_b': 'Intérprete',
  'opcion_c': 'Ensamblador',
  'opcion_d': 'Depurador',
  'pregunta': '¿Qué componente traduce código de alto nivel a lenguaje máquina?',
  'resultado': 'Compilador'},
 {'opcion_a': 'FTP',
  'opcion_b': 'TLS',
  'opcion_c': 'SMTP',
  'opcion_d': 'IMAP',
  'pregunta': '¿Qué protocolo cifra todo el tráfico HTTP?',
  'resultado': 'TLS'},
 {'opcion_a': 'Pila',
  'opcion_b': 'Cola',
  'opcion_c': 'Árbol',
  'opcion_d': 'Tabla hash',
  'pregunta': '¿Qué estructura de datos se utiliza para realizar una búsqueda por amplitud?',
  'resultado': 'Cola'},
 {'opcion_a': 'Compilar programas',
  'opcion_b': 'Gestionar recursos de hardware y software',
  'opcion_c': 'Diseñar bases de datos',
  'opcion_d': 'Realizar copias de seguridad',
  'pregunta': '¿Cuál es la finalidad de un sistema operativo?',
  'resultado': 'Gestionar recursos de hardware y software'},
 {'opcion_a': 'ROM',
  'opcion_b': 'RAM',
  'opcion_c': 'Flash',
  'opcion_d': 'SSD',
  'pregunta': '¿Qué tipo de memoria es volátil?',
  'resultado': 'RAM'},
 {'opcion_a': 'Ejecutar múltiples sistemas operativos en el mismo hardware',
  'opcion_b': 'Crear aplicaciones móviles',
  'opcion_c': 'Incrementar la velocidad de la CPU',
  'opcion_d': 'Reducir el tamaño de la RAM',
  'pregunta': '¿Cuál es el propósito de la virtualización?',
  'resultado': 'Ejecutar múltiples sistemas operativos en el mismo hardware'},
 {'opcion_a': 'Java',
  'opcion_b': 'C',
  'opcion_c': 'Python',
  'opcion_d': 'Go',
  'pregunta': '¿En qué lenguaje está escrito principalmente el núcleo de Linux?',
  'resultado': 'C'},
 {'opcion_a': 'Un bucle infinito en el código fuente',
  'opcion_b': 'Cuando dos o más procesos se bloquean mutuamente',
  'opcion_c': 'Una interrupción de hardware inesperada',
  'opcion_d': 'Un error en la tabla de páginas',
  'pregunta': '¿Qué es un deadlock en sistemas operativos?',
  'resultado': 'Cuando dos o más procesos se bloquean mutuamente'},
 {'opcion_a': 'Hub',
  'opcion_b': 'Switch',
  'opcion_c': 'Router',
  'opcion_d': 'Repeater',
  'pregunta': '¿Qué dispositivo se utiliza para conectar redes con diferentes protocolos?',
  'resultado': 'Router'},
 {'opcion_a': 'Paginación',
  'opcion_b': 'Bloqueo mutuo',
  'opcion_c': 'Segmentación',
  'opcion_d': 'Fragmentación',
  'pregunta': '¿Qué técnica de concurrencia evita condiciones de carrera?',
  'resultado': 'Bloqueo mutuo'},
 {'opcion_a': 'Máquinas virtuales completas',
  'opcion_b': 'Contenedores ligeros',
  'opcion_c': 'Hypervisores dedicados',
  'opcion_d': 'Redes físicas',
  'pregunta': '¿Qué característica ofrece Docker para aislar aplicaciones?',
  'resultado': 'Contenedores ligeros'},
 {'opcion_a': 'Optimizar la velocidad del procesador',
  'opcion_b': 'Bloquear o permitir tráfico de red',
  'opcion_c': 'Encriptar archivos locales',
  'opcion_d': 'Monitorizar consumo de RAM',
  'pregunta': '¿Cuál es la utilidad principal de un firewall?',
  'resultado': 'Bloquear o permitir tráfico de red'},
 {'opcion_a': 'git push',
  'opcion_b': 'git merge',
  'opcion_c': 'git clone',
  'opcion_d': 'git status',
  'pregunta': '¿Qué comando de Git se usa para combinar ramas?',
  'resultado': 'git merge'},
 {'opcion_a': 'El tamaño de la cabecera',
  'opcion_b': 'La cantidad de direcciones disponibles',
  'opcion_c': 'El uso de TCP',
  'opcion_d': 'La utilización de puertos',
  'pregunta': '¿Cuál es la principal diferencia entre IPv4 e IPv6?',
  'resultado': 'La cantidad de direcciones disponibles'},
 {'opcion_a': 'Divide y vencerás',
  'opcion_b': 'Memorización de subproblemas',
  'opcion_c': 'Aleatorización',
  'opcion_d': 'Simulación',
  'pregunta': '¿Qué técnica utiliza la programación dinámica?',
  'resultado': 'Memorización de subproblemas'},
 {'opcion_a': 'Cola de prioridad',
  'opcion_b': 'Pila',
  'opcion_c': 'Lista enlazada',
  'opcion_d': 'Árbol de expansión',
  'pregunta': '¿Qué estructura de datos prioriza la extracción del elemento de mayor peso?',
  'resultado': 'Cola de prioridad'},
 {'opcion_a': 'Terraform',
  'opcion_b': 'Photoshop',
  'opcion_c': 'Blender',
  'opcion_d': 'Illustrator',
  'pregunta': '¿Qué herramienta se emplea para la automatización de infraestructuras como código?',
  'resultado': 'Terraform'},
 {'opcion_a': 'Quicksort',
  'opcion_b': 'Heapsort',
  'opcion_c': 'Mergesort',
  'opcion_d': 'Shellsort',
  'pregunta': '¿Cuál de los siguientes es un algoritmo de ordenamiento estable?',
  'resultado': 'Mergesort'},
 {'opcion_a': 'NTFS',
  'opcion_b': 'FAT32',
  'opcion_c': 'ext4',
  'opcion_d': 'HFS+',
  'pregunta': '¿Qué sistema de archivos es común en Linux?',
  'resultado': 'ext4'},
 {'opcion_a': 'XSS',
  'opcion_b': 'SQL Injection',
  'opcion_c': 'Phishing',
  'opcion_d': 'DDoS',
  'pregunta': '¿Qué tipo de ataque explota la inyección de código en la base de datos?',
  'resultado': 'SQL Injection'},
 {'opcion_a': 'Transporte',
  'opcion_b': 'Presentación',
  'opcion_c': 'Enlace',
  'opcion_d': 'Red',
  'pregunta': '¿Qué capa del modelo OSI se encarga de traducir y cifrar datos para la red?',
  'resultado': 'Presentación'},
 {'opcion_a': 'Mejorar la compresión de datos',
  'opcion_b': 'Incrementar la velocidad de la CPU',
  'opcion_c': 'Garantizar la integridad tras un fallo',
  'opcion_d': 'Reducir el ruido del disco',
  'pregunta': '¿Cuál es la principal ventaja de los sistemas de archivos journaling?',
  'resultado': 'Garantizar la integridad tras un fallo'},
 {'opcion_a': 'Python',
  'opcion_b': 'C++',
  'opcion_c': 'Java',
  'opcion_d': 'C',
  'pregunta': '¿En qué lenguaje está escrita principalmente la máquina virtual de Java?',
  'resultado': 'C++'},
 {'opcion_a': 'Uno que considera todas las soluciones posibles',
  'opcion_b': 'Uno que elige la mejor opción local en cada paso',
  'opcion_c': 'Uno que usa recursión excesiva',
  'opcion_d': 'Uno que carece de estructura',
  'pregunta': '¿Qué es un algoritmo voraz?',
  'resultado': 'Uno que elige la mejor opción local en cada paso'},
 {'opcion_a': 'Planificador',
  'opcion_b': 'Gestor de memoria',
  'opcion_c': 'Driver de red',
  'opcion_d': 'Administrador de archivos',
  'pregunta': '¿Qué componente se encarga de traducir direcciones lógicas a físicas en un sistema operativo?',
  'resultado': 'Gestor de memoria'},
 {'opcion_a': 'RSA',
  'opcion_b': 'AES',
  'opcion_c': 'DSA',
  'opcion_d': 'ECC',
  'pregunta': '¿Cuál de los siguientes es un algoritmo de cifrado simétrico?',
  'resultado': 'AES'},
 {'opcion_a': 'Incrementar la memoria RAM',
  'opcion_b': 'Distribuir tráfico entre varios servidores',
  'opcion_c': 'Optimizar consultas SQL',
  'opcion_d': 'Analizar logs de errores',
  'pregunta': '¿Qué utilidad tiene un balanceador de carga?',
  'resultado': 'Distribuir tráfico entre varios servidores'},
 {'opcion_a': 'Crear múltiples instancias sin control',
  'opcion_b': 'Garantizar una única instancia de una clase',
  'opcion_c': 'Simplificar la herencia múltiple',
  'opcion_d': 'Aumentar la velocidad de la red',
  'pregunta': '¿Cuál es la finalidad del patrón de diseño Singleton?',
  'resultado': 'Garantizar una única instancia de una clase'},
 {'opcion_a': 'Compilado estrictamente',
  'opcion_b': 'Interpretado y de tipado dinámico',
  'opcion_c': 'Exclusivamente para sistemas embebidos',
  'opcion_d': 'Orientado solo a objetos',
  'pregunta': '¿Qué tipo de lenguaje es Python?',
  'resultado': 'Interpretado y de tipado dinámico'},
 {'opcion_a': 'Para almacenar datos en caché cerca del usuario',
  'opcion_b': 'Para crear contenedores de Docker',
  'opcion_c': 'Para compilar código en la nube',
  'opcion_d': 'Para ejecutar scripts de base de datos',
  'pregunta': '¿Para qué se utiliza un CDN?',
  'resultado': 'Para almacenar datos en caché cerca del usuario'},
 {'opcion_a': 'Compilar aplicaciones Java',
  'opcion_b': 'Administrar dependencias de Node.js',
  'opcion_c': 'Crear máquinas virtuales',
  'opcion_d': 'Diseñar interfaces web sin código',
  'pregunta': '¿Qué función cumple el gestor de paquetes npm?',
  'resultado': 'Administrar dependencias de Node.js'},
 {'opcion_a': 'Reducir la redundancia y mejorar la integridad',
  'opcion_b': 'Cifrar información crítica',
  'opcion_c': 'Incrementar el rendimiento de CPU',
  'opcion_d': 'Disminuir la cantidad de queries',
  'pregunta': '¿Qué es la normalización en bases de datos?',
  'resultado': 'Reducir la redundancia y mejorar la integridad'},
 {'opcion_a': 'Haskell',
  'opcion_b': 'C#',
  'opcion_c': 'PHP',
  'opcion_d': 'Bash',
  'pregunta': '¿Cuál es un ejemplo de lenguaje de programación funcional?',
  'resultado': 'Haskell'},
 {'opcion_a': 'No repetir código innecesariamente',
  'opcion_b': 'Documentar cada línea del programa',
  'opcion_c': 'Usar variables globales por defecto',
  'opcion_d': 'Configurar entornos virtuales',
  'pregunta': '¿Qué define el principio DRY en programación?',
  'resultado': 'No repetir código innecesariamente'},
 {'opcion_a': 'Análisis asintótico',
  'opcion_b': 'Instrumentación de hardware',
  'opcion_c': 'Depuración en vivo',
  'opcion_d': 'Compilación cruzada',
  'pregunta': '¿Qué instrumento se utiliza para medir el rendimiento de un algoritmo?',
  'resultado': 'Análisis asintótico'},
 {'opcion_a': 'CloudFormation',
  'opcion_b': 'VirtualBox',
  'opcion_c': 'Kubernetes',
  'opcion_d': 'Ansible',
  'pregunta': '¿Qué tecnología se usa para definir infraestructura en la nube mediante plantillas de AWS?',
  'resultado': 'CloudFormation'},
 {'opcion_a': 'Waterfall',
  'opcion_b': 'Ágil',
  'opcion_c': 'Espiral tradicional',
  'opcion_d': 'Prototipado desechable',
  'pregunta': '¿Qué metodología de desarrollo se basa en iteraciones cortas y feedback continuo?',
  'resultado': 'Ágil'},
 {'opcion_a': 'Un framework de backend',
  'opcion_b': 'Un orquestador de contenedores',
  'opcion_c': 'Una base de datos relacional',
  'opcion_d': 'Un lenguaje de programación',
  'pregunta': '¿Qué es Kubernetes?',
  'resultado': 'Un orquestador de contenedores'},
 {'opcion_a': 'Dirección MAC',
  'opcion_b': 'Dirección IP',
  'opcion_c': 'Nombre de dominio',
  'opcion_d': 'Máscara de subred',
  'pregunta': '¿Qué elemento de una red identifica de forma única a un dispositivo en Internet?',
  'resultado': 'Dirección IP'},
 {'opcion_a': 'Verificar la interfaz de usuario',
  'opcion_b': 'Comprobar el flujo interno del código',
  'opcion_c': 'Probar la integración con la base de datos',
  'opcion_d': 'Validar los requisitos del cliente',
  'pregunta': '¿Cuál es el objetivo de la prueba de caja blanca?',
  'resultado': 'Comprobar el flujo interno del código'},
 {'opcion_a': 'Unidad de control',
  'opcion_b': 'ALU',
  'opcion_c': 'Cache',
  'opcion_d': 'Registro de programa',
  'pregunta': '¿Qué componente del CPU ejecuta operaciones aritméticas y lógicas?',
  'resultado': 'ALU'},
 {'opcion_a': 'Un método para ordenamiento rápido',
  'opcion_b': 'Una técnica de cifrado de clave pública',
  'opcion_c': 'Una función que mapea datos a valores fijos',
  'opcion_d': 'Un protocolo de red',
  'pregunta': '¿Qué es el hashing?',
  'resultado': 'Una función que mapea datos a valores fijos'},
 {'opcion_a': 'Escanear puertos',
  'opcion_b': 'Verificar la conectividad de red',
  'opcion_c': 'Descargar archivos',
  'opcion_d': 'Actualizar paquetes',
  'pregunta': '¿Para qué sirve el comando ping?',
  'resultado': 'Verificar la conectividad de red'},
 {'opcion_a': 'Programación orientada a objetos',
  'opcion_b': 'Programación reactiva',
  'opcion_c': 'Programación imperativa',
  'opcion_d': 'Programación declarativa',
  'pregunta': '¿Qué paradigma se basa en eventos y observadores?',
  'resultado': 'Programación reactiva'},
 {'opcion_a': 'Aplicación de Procesamiento Integrado',
  'opcion_b': 'Interfaz de Programación de Aplicaciones',
  'opcion_c': 'Acceso Público Inmediato',
  'opcion_d': 'Asociación de Programadores Internacionales',
  'pregunta': '¿Qué significa API?',
  'resultado': 'Interfaz de Programación de Aplicaciones'},
 {'opcion_a': 'Una base de datos distribuida',
  'opcion_b': 'Una llamada HTTP que se ejecuta ante un evento',
  'opcion_c': 'Un tipo de contenedor ligero',
  'opcion_d': 'Un protocolo de cifrado asimétrico',
  'pregunta': '¿Qué es un webhook?',
  'resultado': 'Una llamada HTTP que se ejecuta ante un evento'},
 {'opcion_a': '802.15',
  'opcion_b': '802.11',
  'opcion_c': '802.3',
  'opcion_d': '802.1X',
  'pregunta': '¿Qué estándar define las redes inalámbricas Wi-Fi?',
  'resultado': '802.11'},
 {'opcion_a': 'Dividir un problema en subproblemas independientes',
  'opcion_b': 'Duplicar la memoria para resolver más rápido',
  'opcion_c': 'Reducir la tasa de errores de hardware',
  'opcion_d': 'Eliminar la recursión en algoritmos',
  'pregunta': '¿En qué consiste la técnica de divide y vencerás?',
  'resultado': 'Dividir un problema en subproblemas independientes'},
 {'opcion_a': 'Random Access for Input Data',
  'opcion_b': 'Redundant Array of Independent Disks',
  'opcion_c': 'Remote Application Interface Device',
  'opcion_d': 'Rapid Access to Important Data',
  'pregunta': '¿Qué significa la sigla RAID en almacenamiento?',
  'resultado': 'Redundant Array of Independent Disks'},
 {'opcion_a': 'FTP',
  'opcion_b': 'SFTP',
  'opcion_c': 'Telnet',
  'opcion_d': 'SNMP',
  'pregunta': '¿Cuál de estos protocolos se utiliza para transferir archivos de manera segura?',
  'resultado': 'SFTP'},
 {'opcion_a': 'Una columna que puede contener valores duplicados',
  'opcion_b': 'Una columna o conjunto que identifica de manera única cada fila',
  'opcion_c': 'Una clave ajena que referencia otra tabla',
  'opcion_d': 'Un índice sin restricciones',
  'pregunta': '¿Qué es una clave primaria en una base de datos?',
  'resultado': 'Una columna o conjunto que identifica de manera única cada fila'},
 {'opcion_a': 'Docker',
  'opcion_b': 'LXC',
  'opcion_c': 'Kubernetes',
  'opcion_d': 'OpenVZ',
  'pregunta': '¿Qué herramienta de contenedores desarrolló Google?',
  'resultado': 'Kubernetes'},
 {'opcion_a': 'Un software que se ejecuta en la nube',
  'opcion_b': 'Un sistema dedicado a una función específica dentro de un dispositivo',
  'opcion_c': 'Un programa de escritorio que maneja bases de datos',
  'opcion_d': 'Un servicio web de autenticación',
  'pregunta': '¿Qué es un sistema embebido?',
  'resultado': 'Un sistema dedicado a una función específica dentro de un dispositivo'},
 {'opcion_a': 'chmod',
  'opcion_b': 'ls',
  'opcion_c': 'rm',
  'opcion_d': 'mv',
  'pregunta': '¿Qué comando en Linux cambia los permisos de un archivo?',
  'resultado': 'chmod'},
 {'opcion_a': 'CNN',
  'opcion_b': 'RNN',
  'opcion_c': 'SVM',
  'opcion_d': 'KNN',
  'pregunta': '¿Cuál de las siguientes es una red neuronal recurrente?',
  'resultado': 'RNN'},
 {'opcion_a': 'Clientes y servidores comparten la misma memoria',
  'opcion_b': 'Los clientes solicitan servicios que los servidores proveen',
  'opcion_c': 'Los servidores sólo sirven archivos de texto',
  'opcion_d': 'No se utiliza en aplicaciones web',
  'pregunta': '¿Qué define la arquitectura cliente-servidor?',
  'resultado': 'Los clientes solicitan servicios que los servidores proveen'},
 {'opcion_a': 'El compilado se ejecuta línea por línea',
  'opcion_b': 'El compilado se traduce antes de ejecutarse',
  'opcion_c': 'El interpretado produce archivos binarios',
  'opcion_d': 'El interpretado necesita un preprocesador',
  'pregunta': '¿Qué característica distingue a un lenguaje compilado de uno interpretado?',
  'resultado': 'El compilado se traduce antes de ejecutarse'},
 {'opcion_a': 'Byte',
  'opcion_b': 'Bit',
  'opcion_c': 'Palabra',
  'opcion_d': 'Registro',
  'pregunta': '¿Cuál es la unidad mínima de información en un computador?',
  'resultado': 'Bit'},
 {'opcion_a': 'Representational State Transfer',
  'opcion_b': 'Random Extended Simulation Tool',
  'opcion_c': 'Reliable Service Transport',
  'opcion_d': 'Recursive Software Technique',
  'pregunta': '¿Qué significa REST en el contexto de APIs?',
  'resultado': 'Representational State Transfer'},
 {'opcion_a': 'El libre permite modificar y el abierto no',
  'opcion_b': 'Ambos son idénticos en definiciones',
  'opcion_c': 'El software libre se centra en la libertad, el de código abierto en el modelo de desarrollo',
  'opcion_d': 'El abierto no permite uso comercial',
  'pregunta': '¿Cuál es la diferencia principal entre software libre y software de código abierto?',
  'resultado': 'El software libre se centra en la libertad, el de código abierto en el modelo de desarrollo'},
 {'opcion_a': 'Asignar direcciones IP automáticamente',
  'opcion_b': 'Encriptar tráfico de red',
  'opcion_c': 'Administrar cuentas de usuario',
  'opcion_d': 'Monitorizar uso de CPU',
  'pregunta': '¿Cuál es la finalidad del protocolo DHCP?',
  'resultado': 'Asignar direcciones IP automáticamente'},
 {'opcion_a': 'Permite recorrido en ambos sentidos',
  'opcion_b': 'Almacena elementos de forma continua en memoria',
  'opcion_c': 'Solo permite inserción al final',
  'opcion_d': 'No posee punteros',
  'pregunta': '¿Qué propiedad tiene una lista enlazada doblemente ligada?',
  'resultado': 'Permite recorrido en ambos sentidos'},
 {'opcion_a': 'Ordenamiento por inserción',
  'opcion_b': 'Mantenerse balanceado mediante rotaciones',
  'opcion_c': 'Almacenamiento sin claves',
  'opcion_d': 'Búsqueda por hashing',
  'pregunta': '¿Qué estrategia usa un árbol AVL?',
  'resultado': 'Mantenerse balanceado mediante rotaciones'},
 {'opcion_a': 'Crear discos duros virtuales',
  'opcion_b': 'Configurar redes completamente mediante software',
  'opcion_c': 'Multiplicar la frecuencia de reloj',
  'opcion_d': 'Generar direcciones IP aleatorias',
  'pregunta': '¿En qué consiste la virtualización de red?',
  'resultado': 'Configurar redes completamente mediante software'},
 {'opcion_a': 'Un sistema para bases de datos en la nube',
  'opcion_b': 'Almacena datos en múltiples nodos de red',
  'opcion_c': 'Una política de encriptación',
  'opcion_d': 'Un protocolo de mensajería',
  'pregunta': '¿Qué es un sistema de archivos distribuido?',
  'resultado': 'Almacena datos en múltiples nodos de red'},
 {'opcion_a': 'Programación orientada a objetos',
  'opcion_b': 'Computación distribuida',
  'opcion_c': 'Bases de datos relacionales',
  'opcion_d': 'Arquitectura cliente-servidor',
  'pregunta': '¿Qué paradigma se asocia con MapReduce?',
  'resultado': 'Computación distribuida'},
 {'opcion_a': 'Un servidor de bases de datos monolítico',
  'opcion_b': 'Un componente independiente con una única responsabilidad',
  'opcion_c': 'Un script de automatización',
  'opcion_d': 'Una aplicación de escritorio',
  'pregunta': '¿Cuál de las siguientes opciones describe mejor un microservicio?',
  'resultado': 'Un componente independiente con una única responsabilidad'},
 {'opcion_a': 'Falso',
  'opcion_b': 'Verdadero',
  'opcion_c': 'Nulo',
  'opcion_d': 'Indeterminado',
  'pregunta': '¿Qué valor de verdad devuelve la operación OR cuando uno de los operandos es verdadero?',
  'resultado': 'Verdadero'},
 {'opcion_a': 'Aplicación',
  'opcion_b': 'Transporte',
  'opcion_c': 'Enlace de datos',
  'opcion_d': 'Física',
  'pregunta': '¿En qué capa del modelo OSI trabaja un switch?',
  'resultado': 'Enlace de datos'},
 {'opcion_a': 'cgroups y namespaces',
  'opcion_b': 'cron y systemd',
  'opcion_c': 'iptables y nftables',
  'opcion_d': 'gcc y make',
  'pregunta': '¿Qué se usa para aislar procesos en Linux además de contenedores?',
  'resultado': 'cgroups y namespaces'},
 {'opcion_a': 'Cola',
  'opcion_b': 'Pila',
  'opcion_c': 'Lista doble',
  'opcion_d': 'Hash table',
  'pregunta': '¿Qué estructura de datos se utiliza para un recorrido en profundidad en grafos?',
  'resultado': 'Pila'},
 {'opcion_a': 'Prefetching',
  'opcion_b': 'Pipelining',
  'opcion_c': 'Caching',
  'opcion_d': 'Hyper-threading',
  'pregunta': '¿Qué técnica optimiza el rendimiento de la CPU almacenando instrucciones recientes?',
  'resultado': 'Caching'},
 {'opcion_a': 'FTP',
  'opcion_b': 'DNS',
  'opcion_c': 'DHCP',
  'opcion_d': 'SMTP',
  'pregunta': '¿Qué protocolo se utiliza para la resolución de nombres de dominio?',
  'resultado': 'DNS'},
 {'opcion_a': 'Swift',
  'opcion_b': 'Kotlin',
  'opcion_c': 'Ruby',
  'opcion_d': 'Objective-C',
  'pregunta': '¿Qué lenguaje se emplea para el desarrollo de aplicaciones Android?',
  'resultado': 'Kotlin'},
 {'opcion_a': 'Atomicidad',
  'opcion_b': 'Durabilidad',
  'opcion_c': 'Aislamiento',
  'opcion_d': 'Consistencia',
  'pregunta': '¿Qué concepto en bases de datos permite asegurar que cada transacción se realiza completamente o no se '
              'realiza?',
  'resultado': 'Atomicidad'},
 {'opcion_a': 'Top',
  'opcion_b': 'Traceroute',
  'opcion_c': 'Df',
  'opcion_d': 'Ls',
  'pregunta': '¿Qué instrumento se utiliza para medir la latencia de una red?',
  'resultado': 'Traceroute'},
 {'opcion_a': 'Disminuir el consumo de memoria',
  'opcion_b': 'Aprovechar mejor los recursos disponibles',
  'opcion_c': 'Evitar la duplicación de código',
  'opcion_d': 'Simplificar la lógica de la aplicación',
  'pregunta': '¿Cuál es la principal ventaja de la programación concurrente?',
  'resultado': 'Aprovechar mejor los recursos disponibles'},
 {'opcion_a': 'Un software para monitorizar redes',
  'opcion_b': 'Un conjunto de líneas que transportan información entre componentes',
  'opcion_c': 'Un protocolo de comunicación inalámbrico',
  'opcion_d': 'Una memoria volátil de alta velocidad',
  'pregunta': '¿Qué es un bus de datos?',
  'resultado': 'Un conjunto de líneas que transportan información entre componentes'},
 {'opcion_a': 'Un programa que gestiona máquinas virtuales',
  'opcion_b': 'Una herramienta para editar imágenes',
  'opcion_c': 'Un dispositivo de red',
  'opcion_d': 'Una librería de Java',
  'pregunta': '¿Qué es un hipervisor?',
  'resultado': 'Un programa que gestiona máquinas virtuales'},
 {'opcion_a': 'Quicksort',
  'opcion_b': 'Bubblesort',
  'opcion_c': 'Insertion sort',
  'opcion_d': 'Selection sort',
  'pregunta': '¿Qué algoritmo ordena usando particiones y recursión?',
  'resultado': 'Quicksort'},
 {'opcion_a': 'Una clave compartida para cifrado',
  'opcion_b': 'Un identificador que otorga permisos o acceso',
  'opcion_c': 'Un tipo de malware',
  'opcion_d': 'Un protocolo de red',
  'pregunta': '¿Qué es un token en seguridad informática?',
  'resultado': 'Un identificador que otorga permisos o acceso'},
 {'opcion_a': 'Xen',
  'opcion_b': 'LXC',
  'opcion_c': 'VMware',
  'opcion_d': 'Hyper-V',
  'pregunta': '¿Qué tecnología se utiliza para contenedores ligeros en el kernel de Linux?',
  'resultado': 'LXC'},
 {'opcion_a': 'Almacenar datos de respaldo',
  'opcion_b': 'Gestionar las peticiones antes de llegar al servidor',
  'opcion_c': 'Analizar datos de usuario',
  'opcion_d': 'Ejecutar scripts en el cliente',
  'pregunta': '¿Cuál es el objetivo principal de un proxy inverso?',
  'resultado': 'Gestionar las peticiones antes de llegar al servidor'},
 {'opcion_a': 'El compilador',
  'opcion_b': 'El planificador de consultas',
  'opcion_c': 'El sistema de transacciones',
  'opcion_d': 'El gestor de vistas',
  'pregunta': '¿Qué componente de bases de datos asegura la coherencia de los datos?',
  'resultado': 'El sistema de transacciones'},
 {'opcion_a': 'Genera código optimizado',
  'opcion_b': 'Convierte una secuencia de caracteres en tokens',
  'opcion_c': 'Organiza archivos en carpetas',
  'opcion_d': 'Ejecuta el programa paso a paso',
  'pregunta': '¿Qué hace un analizador léxico?',
  'resultado': 'Convierte una secuencia de caracteres en tokens'},
 {'opcion_a': 'Reducir la latencia de red',
  'opcion_b': 'Mantener un servicio activo ante fallos del sistema',
  'opcion_c': 'Aumentar la velocidad de la CPU',
  'opcion_d': 'Compartir impresoras',
  'pregunta': '¿Cuál es la finalidad de un clúster de alta disponibilidad?',
  'resultado': 'Mantener un servicio activo ante fallos del sistema'},
 {'opcion_a': 'Uno que optimiza con métodos heurísticos',
  'opcion_b': 'Uno que prueba todas las soluciones posibles',
  'opcion_c': 'Uno que analiza grafos dirigidos',
  'opcion_d': 'Uno que simula procesos físicos',
  'pregunta': '¿Qué es un algoritmo de fuerza bruta?',
  'resultado': 'Uno que prueba todas las soluciones posibles'},
 {'opcion_a': 'Cibernética',
  'opcion_b': 'Inteligencia artificial',
  'opcion_c': 'Bioinformática',
  'opcion_d': 'Ingeniería de software',
  'pregunta': '¿Cómo se llama la ciencia que estudia la creación de máquinas capaces de realizar tareas que requieren '
              'inteligencia humana?',
  'resultado': 'Inteligencia artificial'},
 {'opcion_a': 'Un protocolo de enrutamiento',
  'opcion_b': 'Un documento digital que autentica la identidad y cifra comunicaciones',
  'opcion_c': 'Un algoritmo de compresión',
  'opcion_d': 'Un formato de imagen',
  'pregunta': '¿Qué es un certificado SSL?',
  'resultado': 'Un documento digital que autentica la identidad y cifra comunicaciones'},
 {'opcion_a': 'Fortran',
  'opcion_b': 'Python',
  'opcion_c': 'Pascal',
  'opcion_d': 'Visual Basic',
  'pregunta': '¿Qué lenguaje de programación es popular para análisis de datos y aprendizaje automático?',
  'resultado': 'Python'},
 {'opcion_a': 'Pequeños conjuntos de datos simples',
  'opcion_b': 'Conjuntos de datos tan grandes y complejos que requieren técnicas especiales',
  'opcion_c': 'La velocidad de Internet en redes de fibra',
  'opcion_d': 'Archivos comprimidos de video',
  'pregunta': '¿Cuál es la definición de big data?',
  'resultado': 'Conjuntos de datos tan grandes y complejos que requieren técnicas especiales'}]

with sqlite3.connect(DB_PATH) as conn:
    cur = conn.cursor()
    cur.execute('DELETE FROM preguntas')
    for p in preguntas:
        cur.execute(
            'INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, resultado) VALUES (?, ?, ?, ?, ?, ?)',
            (p['pregunta'], p['opcion_a'], p['opcion_b'], p['opcion_c'], p['opcion_d'], p['resultado'])
        )
    conn.commit()
print(f"Insertadas {len(preguntas)} preguntas de prueba")
